import type { Language, Difficulty, BugPuzzle } from '../content/types';
import { getPuzzlesByLanguage } from '../content/puzzles';
import { validatePuzzle } from '../content/validator';
import { AI_TIMEOUT_MS } from '../engine/constants';

export interface GenerateResult {
  puzzle: BugPuzzle;
  isAiGenerated: boolean;
  message?: string;
}

/**
 * Generates an AI bug puzzle or falls back gracefully to a curated puzzle.
 */
export function getRandomCuratedPuzzle(language: Language, difficulty?: Difficulty): BugPuzzle {
  const pool = getPuzzlesByLanguage(language);
  const filtered = difficulty ? pool.filter((p) => p.difficulty === difficulty) : pool;
  const targetPool = filtered.length > 0 ? filtered : pool;
  const randomIndex = Math.floor(Math.random() * targetPool.length);
  return targetPool[randomIndex];
}

export async function requestBugPuzzle(
  language: Language,
  difficulty: Difficulty = 1,
): Promise<GenerateResult> {
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), AI_TIMEOUT_MS);

    const response = await fetch('/api/generate-bug', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ language, difficulty }),
      signal: controller.signal,
    });

    clearTimeout(timeout);

    if (response.ok) {
      const data = await response.json();
      if (!data.fallback && data.puzzle) {
        const validation = validatePuzzle(data.puzzle);
        if (validation.valid) {
          return {
            puzzle: data.puzzle,
            isAiGenerated: true,
            message: 'Fresh AI bug generated by Google Gemini!',
          };
        }
      }
    }

    // Graceful fallback to curated bank
    return {
      puzzle: getRandomCuratedPuzzle(language, difficulty),
      isAiGenerated: false,
      message: 'Using verified offline puzzle bank.',
    };
  } catch {
    return {
      puzzle: getRandomCuratedPuzzle(language, difficulty),
      isAiGenerated: false,
      message: 'Network offline. Using verified puzzle bank.',
    };
  }
}
