import type { BugPuzzle } from '../types';

export const JAVASCRIPT_PUZZLES: BugPuzzle[] = [
  {
    id: 'js-01-loose-equality',
    title: 'Strict Pin Check',
    language: 'javascript',
    category: 'comparison_error',
    difficulty: 1,
    concept: 'Loose equality (==) vs strict equality (===)',
    brief: 'Only accept the security PIN if it is provided as a number, not text.',
    buggyCode: `function verifyPin(inputPin, systemPin) {\n  return inputPin == systemPin;\n}\n\nconsole.log(verifyPin("1234", 1234));`,
    bugLineNumber: 2,
    expectedOutput: 'false',
    actualOutput: 'true',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '  return inputPin === systemPin;',
        explanation: 'Strict equality (===) checks both value and type without coercing strings to numbers.',
      },
      {
        id: 'opt-b',
        codeReplacement: '  return inputPin = systemPin;',
        explanation: 'Single = is assignment, which mutates inputPin and returns the value.',
      },
      {
        id: 'opt-c',
        codeReplacement: '  return String(inputPin) == systemPin;',
        explanation: 'Converts inputPin to string and still does loose coercion.',
      },
      {
        id: 'opt-d',
        codeReplacement: '  return inputPin !== systemPin;',
        explanation: 'Inverts the condition entirely, returning true when unequal.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Why did string "1234" match number 1234?',
      'JavaScript loose equality (==) coerces different types before comparing.',
      'Use triple equals (===) to demand identical types and values.',
    ],
    explanation:
      'The double-equals `==` operator performs type coercion, turning the string "1234" into number 1234. Strict equality `===` preserves type safety.',
    creature: {
      id: 'c-coercio',
      name: 'Coercio',
      species: 'Chameleon Fox',
      rarity: 'common',
      description: 'Disguises strings as numbers to slip through security checkpoints.',
      avatarEmoji: '🦊',
    },
  },
  {
    id: 'js-02-sort-numbers',
    title: 'Leaderboard Ranking',
    language: 'javascript',
    category: 'logic_error',
    difficulty: 2,
    concept: 'Array.prototype.sort() string conversion default',
    brief: 'Sort an array of numeric scores in ascending order.',
    buggyCode: `function sortScores(scores) {\n  return scores.sort();\n}\n\nconst pts = [25, 8, 100, 3];\nconsole.log(sortScores(pts));`,
    bugLineNumber: 2,
    expectedOutput: '[3, 8, 25, 100]',
    actualOutput: '[100, 25, 3, 8]',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '  return scores.sort((a, b) => a - b);',
        explanation: 'Supplying a comparator function (a, b) => a - b sorts numerically.',
      },
      {
        id: 'opt-b',
        codeReplacement: '  return scores.sort().reverse();',
        explanation: 'Reversing lexicographical sort gives ["8", "3", "25", "100"], not descending math.',
      },
      {
        id: 'opt-c',
        codeReplacement: '  return scores.sort((a, b) => a + b);',
        explanation: 'Addition comparator does not produce standard negative/positive order values.',
      },
      {
        id: 'opt-d',
        codeReplacement: '  return scores.toSorted();',
        explanation: 'toSorted() without comparator still defaults to string alphabetical sorting.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Look at why 100 came before 25 and 3.',
      'Default .sort() converts elements to strings and compares UTF-16 code units ("1" < "2" < "3").',
      'Provide a numeric comparator function: `(a, b) => a - b`.',
    ],
    explanation:
      'By default, JavaScript `Array.prototype.sort()` converts elements to strings and compares them lexicographically. To sort numbers, pass a comparator `(a, b) => a - b`.',
    creature: {
      id: 'c-lexicotaur',
      name: 'Lexicotaur',
      species: 'Dictionary Beast',
      rarity: 'rare',
      description: 'Insists that 100 is smaller than 2 because "1" comes before "2" in the alphabet.',
      avatarEmoji: '🐂',
    },
  },
  {
    id: 'js-03-var-hoisting',
    title: 'Delayed Countdown Timers',
    language: 'javascript',
    category: 'variable_scope',
    difficulty: 2,
    concept: 'var function scope vs let block scope in loops',
    brief: 'Record 3 numbers from loop iterations into an array.',
    buggyCode: `function makeCounters() {\n  const results = [];\n  for (var i = 0; i < 3; i++) {\n    results.push(() => i);\n  }\n  return results.map(fn => fn());\n}\nconsole.log(makeCounters());`,
    bugLineNumber: 3,
    expectedOutput: '[0, 1, 2]',
    actualOutput: '[3, 3, 3]',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '  for (let i = 0; i < 3; i++) {',
        explanation: 'let is block-scoped, binding a fresh i variable for each loop iteration.',
      },
      {
        id: 'opt-b',
        codeReplacement: '  for (const i = 0; i < 3; i++) {',
        explanation: 'const cannot be incremented by i++, throwing TypeError.',
      },
      {
        id: 'opt-c',
        codeReplacement: '  for (var i = 0; i <= 3; i++) {',
        explanation: 'Still uses var, causing all closures to return 4.',
      },
      {
        id: 'opt-d',
        codeReplacement: '  for (i = 0; i < 3; i++) {',
        explanation: 'Omitting declaration creates an accidental global variable with the same problem.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Why did every closure return 3 instead of 0, 1, 2?',
      'Variables declared with `var` are function-scoped, sharing a single binding across the loop.',
      'Replace `var` with `let` to give every iteration its own block-scoped variable.',
    ],
    explanation:
      '`var` is hoisted and function-scoped, meaning all three arrow functions capture the exact same variable `i`. Switching to `let` creates a distinct lexical environment per iteration.',
    creature: {
      id: 'c-hoistgeist',
      name: 'Hoistgeist',
      species: 'Phantom Clock',
      rarity: 'rare',
      description: 'Replaces past timestamps with whatever time it is when the bell tolls.',
      avatarEmoji: '⏳',
    },
  },
  {
    id: 'js-04-undefined-property',
    title: 'User Profile City',
    language: 'javascript',
    category: 'null_undefined',
    difficulty: 1,
    concept: 'Safe property chaining on optional objects',
    brief: 'Return city name from user profile, or "Unknown" if missing.',
    buggyCode: `function getUserCity(user) {\n  return user.address.city || "Unknown";\n}\n\nconst guest = { name: "Sam" };\nconsole.log(getUserCity(guest));`,
    bugLineNumber: 2,
    expectedOutput: 'Unknown',
    actualOutput: "TypeError: Cannot read properties of undefined (reading 'city')",
    options: [
      {
        id: 'opt-a',
        codeReplacement: '  return user.address?.city ?? "Unknown";',
        explanation: 'Optional chaining (?.) safely returns undefined if address is absent.',
      },
      {
        id: 'opt-b',
        codeReplacement: '  return user[address].city || "Unknown";',
        explanation: 'address without quotes is treated as an undeclared variable (ReferenceError).',
      },
      {
        id: 'opt-c',
        codeReplacement: '  return user.address && "Unknown";',
        explanation: 'Returns undefined because address is missing, instead of "Unknown".',
      },
      {
        id: 'opt-d',
        codeReplacement: '  return user.city || "Unknown";',
        explanation: 'Skips the nested address object requirement.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'The guest object has no address property.',
      'Accessing `undefined.city` immediately throws a TypeError.',
      'Use optional chaining `?.` to stop property traversal if address is undefined.',
    ],
    explanation:
      'Accessing properties of `undefined` is one of the most common JavaScript runtime errors. Modern JS provides optional chaining (`?.`) to safely short-circuit.',
    creature: {
      id: 'c-nullbite',
      name: 'Nullbite',
      species: 'Void Mosquito',
      rarity: 'common',
      description: 'Stings the runtime whenever you try to walk through an empty doorway.',
      avatarEmoji: '🦟',
    },
  },
  {
    id: 'js-05-async-missing-await',
    title: 'Async Data Fetcher',
    language: 'javascript',
    category: 'type_error',
    difficulty: 2,
    concept: 'Awaiting Promises in async functions',
    brief: 'Retrieve user data and log their display badge.',
    buggyCode: `async function fetchLevel() {\n  return 42;\n}\n\nasync function showBadge() {\n  const level = fetchLevel();\n  return "Level " + level;\n}\nshowBadge().then(console.log);`,
    bugLineNumber: 6,
    expectedOutput: 'Level 42',
    actualOutput: 'Level [object Promise]',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '  const level = await fetchLevel();',
        explanation: 'Awaiting the promise unwraps the resolved value 42 before concatenation.',
      },
      {
        id: 'opt-b',
        codeReplacement: '  const level = fetchLevel.value;',
        explanation: 'Promises do not expose a .value property directly.',
      },
      {
        id: 'opt-c',
        codeReplacement: '  const level = fetchLevel() || 42;',
        explanation: 'A Promise object is truthy, so || never executes the fallback.',
      },
      {
        id: 'opt-d',
        codeReplacement: '  const level = sync fetchLevel();',
        explanation: 'sync is not a valid JavaScript keyword.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Look at why the output contains "[object Promise]".',
      'Async functions always return a Promise, even if they return a number inside.',
      'Use the `await` keyword inside `showBadge` to pause until the value resolves.',
    ],
    explanation:
      'Every `async` function returns a Promise. When you concatenate a Promise without awaiting it, JavaScript converts it to string `"[object Promise]"`.',
    creature: {
      id: 'c-promisewraith',
      name: 'Promisewraith',
      species: 'Async Phantom',
      rarity: 'rare',
      description: 'Hands you a wrapped gift box instead of the actual toy.',
      avatarEmoji: '📦',
    },
  },
  {
    id: 'js-06-const-reassignment',
    title: 'Counter Increment',
    language: 'javascript',
    category: 'variable_scope',
    difficulty: 1,
    concept: 'const variable re-assignment immutability',
    brief: 'Increment and return the next counter step.',
    buggyCode: `function getNextStep() {\n  const count = 1;\n  count = count + 1;\n  return count;\n}\nconsole.log(getNextStep());`,
    bugLineNumber: 2,
    expectedOutput: '2',
    actualOutput: 'TypeError: Assignment to constant variable.',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '  let count = 1;',
        explanation: 'let allows the variable to be reassigned later in the function.',
      },
      {
        id: 'opt-b',
        codeReplacement: '  const count = 2;',
        explanation: 'Hardcoding 2 breaks dynamic counting logic.',
      },
      {
        id: 'opt-c',
        codeReplacement: '  var count: number = 1;',
        explanation: 'TypeScript type annotation syntax is invalid in standard JS runtime.',
      },
      {
        id: 'opt-d',
        codeReplacement: '  immutable count = 1;',
        explanation: 'immutable is not a valid JS declaration keyword.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Read the error message: "Assignment to constant variable".',
      'Variables declared with `const` cannot have their identifier reassigned.',
      'Use `let` for variables whose values must change over time.',
    ],
    explanation:
      '`const` prevents identifier reassignment. If a primitive variable needs to be updated with new values, declare it with `let`.',
    creature: {
      id: 'c-constrictor',
      name: 'Constrictor',
      species: 'Petrification Snake',
      rarity: 'common',
      description: 'Freezes any variable in stone the millisecond it is created.',
      avatarEmoji: '🐍',
    },
  },
  {
    id: 'js-07-nan-equality',
    title: 'Detect Invalid Input',
    language: 'javascript',
    category: 'comparison_error',
    difficulty: 2,
    concept: 'NaN self-comparison and Number.isNaN()',
    brief: 'Detect when parsed input resulted in an invalid number.',
    buggyCode: `function isBadNumber(val) {\n  return Number(val) === NaN;\n}\n\nconsole.log(isBadNumber("banana"));`,
    bugLineNumber: 2,
    expectedOutput: 'true',
    actualOutput: 'false',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '  return Number.isNaN(Number(val));',
        explanation: 'Number.isNaN() accurately detects whether the value is IEEE-754 NaN.',
      },
      {
        id: 'opt-b',
        codeReplacement: '  return Number(val) == NaN;',
        explanation: 'Even with loose equality ==, NaN is never equal to NaN.',
      },
      {
        id: 'opt-c',
        codeReplacement: '  return val === "NaN";',
        explanation: 'banana is not the literal string "NaN".',
      },
      {
        id: 'opt-d',
        codeReplacement: '  return typeof Number(val) === "nan";',
        explanation: 'typeof NaN is actually "number" in lowercase in JavaScript.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Can NaN ever equal anything using `===`?',
      'In IEEE-754 floating point standard, `NaN === NaN` is uniquely false.',
      'Use the built-in helper method `Number.isNaN(val)`.',
    ],
    explanation:
      '`NaN` is the only value in JavaScript that is not equal to itself (`NaN === NaN` is false). You must use `Number.isNaN()` to check for it.',
    creature: {
      id: 'c-nanomancer',
      name: 'Nanomancer',
      species: 'Paradox Sorcerer',
      rarity: 'rare',
      description: 'Can stare in a mirror and honestly claim they are not who they see.',
      avatarEmoji: '🧙',
    },
  },
  {
    id: 'js-08-array-mutation-splice',
    title: 'Purge Negative Numbers',
    language: 'javascript',
    category: 'array_mutation',
    difficulty: 2,
    concept: 'Pure filtering vs mutating array during traversal',
    brief: 'Return only positive numbers from a list.',
    buggyCode: `function removeNegatives(nums) {\n  return nums.filter(x => x < 0);\n}\n\nconst list = [5, -2, 8, -1, 3];\nconsole.log(removeNegatives(list));`,
    bugLineNumber: 2,
    expectedOutput: '[5, 8, 3]',
    actualOutput: '[-2, -1]',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '  return nums.filter(x => x >= 0);',
        explanation: 'filter keeps elements where the predicate returns true; we want positives.',
      },
      {
        id: 'opt-b',
        codeReplacement: '  return nums.map(x => x < 0);',
        explanation: 'map returns boolean array [false, true, false, true, false].',
      },
      {
        id: 'opt-c',
        codeReplacement: '  return nums.splice(0, 2);',
        explanation: 'splice mutates the original array and cuts off items by index.',
      },
      {
        id: 'opt-d',
        codeReplacement: '  return nums.filter(x => !x);',
        explanation: 'Removes all truthy numbers, leaving only 0.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Look at the condition inside filter: `x < 0`.',
      'The brief asks to remove negatives, meaning you want to KEEP positives (>= 0).',
      'Invert the filter predicate to `x => x >= 0`.',
    ],
    explanation:
      '`Array.prototype.filter` retains elements that evaluate to truthy. Writing `x < 0` kept only the negative values instead of filtering them out.',
    creature: {
      id: 'c-splicer',
      name: 'Inverso Splicer',
      species: 'Inversion Goblin',
      rarity: 'common',
      description: 'Flips your filter nets upside-down so you catch the trash and drop the fish.',
      avatarEmoji: '🎣',
    },
  },
  {
    id: 'js-09-off-by-one',
    title: 'Print All Friends',
    language: 'javascript',
    category: 'off_by_one',
    difficulty: 1,
    concept: 'Loop index boundary (<= vs < length)',
    brief: 'Print each friend name in the list.',
    buggyCode: `function printFriends(friends) {\n  for (let i = 0; i <= friends.length; i++) {\n    console.log(friends[i]);\n  }\n}\nprintFriends(["Mia", "Leo"]);`,
    bugLineNumber: 2,
    expectedOutput: 'Mia\nLeo',
    actualOutput: 'Mia\nLeo\nundefined',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '  for (let i = 0; i < friends.length; i++) {',
        explanation: 'Using strictly less than (<) prevents accessing past the last element.',
      },
      {
        id: 'opt-b',
        codeReplacement: '  for (let i = 1; i <= friends.length; i++) {',
        explanation: 'Starting at 1 skips the first friend "Mia" at index 0.',
      },
      {
        id: 'opt-c',
        codeReplacement: '  for (let i = 0; i < friends.length - 1; i++) {',
        explanation: 'Stops too early, missing "Leo".',
      },
      {
        id: 'opt-d',
        codeReplacement: '  for (let i in friends.length) {',
        explanation: 'for..in on a number primitive produces no iterations.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Notice that the output prints "undefined" after "Leo".',
      'Array length is 2, but valid indices are only 0 and 1.',
      'Change `<=` to `<` so the loop terminates when `i === friends.length`.',
    ],
    explanation:
      'JavaScript arrays are 0-indexed. When `i <= length`, the final iteration reads `arr[length]`, which does not exist and yields `undefined`.',
    creature: {
      id: 'c-fencepost',
      name: 'Fencepost Golem',
      species: 'Boundary Golem',
      rarity: 'common',
      description: 'Plants an extra fence post in the lake where nobody can stand.',
      avatarEmoji: '🪵',
    },
  },
  {
    id: 'js-10-object-pass-by-ref',
    title: 'Safe Settings Mutation',
    language: 'javascript',
    category: 'array_mutation',
    difficulty: 2,
    concept: 'Object reference sharing vs shallow spread copy',
    brief: 'Create modified user config without mutating default config.',
    buggyCode: `function updateTheme(defaults) {\n  const custom = defaults;\n  custom.dark = true;\n  return custom;\n}\nconst base = { dark: false };\nupdateTheme(base);\nconsole.log(base.dark);`,
    bugLineNumber: 2,
    expectedOutput: 'false',
    actualOutput: 'true',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '  const custom = { ...defaults };',
        explanation: 'Object spread operator {...defaults} creates a fresh shallow clone.',
      },
      {
        id: 'opt-b',
        codeReplacement: '  const custom = Object(defaults);',
        explanation: 'Object(defaults) returns the original object unmodified.',
      },
      {
        id: 'opt-c',
        codeReplacement: '  const custom = [defaults];',
        explanation: 'Creates an array wrapping the object instead of copying it.',
      },
      {
        id: 'opt-d',
        codeReplacement: '  const custom = defaults.dark;',
        explanation: 'custom becomes a boolean, crashing custom.dark = true.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Why did `base.dark` change when modifying `custom`?',
      'Variables pointing to objects hold memory references, not independent copies.',
      'Clone the object with `{ ...defaults }` to make mutations isolated.',
    ],
    explanation:
      'In JavaScript, object assignment copies references, not data. Modifying a property on `custom` alters the original `base` object unless spread `{ ...defaults }` is used.',
    creature: {
      id: 'c-shadowclone',
      name: 'Shadowclone',
      species: 'Voodoo Doll',
      rarity: 'epic',
      description: 'Pinches the copy and causes the original across the room to cry out.',
      avatarEmoji: '🎎',
    },
  },
  {
    id: 'js-11-typeof-null',
    title: 'Verify Real Object',
    language: 'javascript',
    category: 'type_error',
    difficulty: 2,
    concept: 'typeof null legacy quirk',
    brief: 'Check whether a value is a valid non-null object.',
    buggyCode: `function isRealObject(item) {\n  return typeof item === "object";\n}\n\nconsole.log(isRealObject(null));`,
    bugLineNumber: 2,
    expectedOutput: 'false',
    actualOutput: 'true',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '  return typeof item === "object" && item !== null;',
        explanation: 'Checks both typeof object and guards against null.',
      },
      {
        id: 'opt-b',
        codeReplacement: '  return typeof item !== "null";',
        explanation: 'typeof null is "object", never "null", so this condition is always true.',
      },
      {
        id: 'opt-c',
        codeReplacement: '  return item instanceof Object;',
        explanation: 'instanceof Object works for objects created from Object, but fails for Object.create(null).',
      },
      {
        id: 'opt-d',
        codeReplacement: '  return Boolean(item);',
        explanation: 'Boolean checks truthiness, so empty objects {} and strings return true.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'What does `typeof null` return in JavaScript?',
      'Due to an infamous 1995 engine bug, `typeof null` evaluates to "object".',
      'Always add `&& item !== null` when testing for object types.',
    ],
    explanation:
      'In JavaScript, `typeof null === "object"` is a famous historical bug that cannot be fixed without breaking web backward compatibility. Always check `item !== null`.',
    creature: {
      id: 'c-typechameleon',
      name: 'Nullchameleon',
      species: 'Lizard Impostor',
      rarity: 'rare',
      description: 'Wears an "I am an Object" badge while secretly being completely empty.',
      avatarEmoji: '🦎',
    },
  },
  {
    id: 'js-12-string-replace-all',
    title: 'Censor Profanity',
    language: 'javascript',
    category: 'string_indexing',
    difficulty: 1,
    concept: 'String.prototype.replace() first match vs replaceAll()',
    brief: 'Replace all occurrences of "bad" with "good".',
    buggyCode: `function cleanText(sentence) {\n  return sentence.replace("bad", "good");\n}\n\nconst text = "bad vibes make bad days";\nconsole.log(cleanText(text));`,
    bugLineNumber: 2,
    expectedOutput: 'good vibes make good days',
    actualOutput: 'good vibes make bad days',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '  return sentence.replaceAll("bad", "good");',
        explanation: 'replaceAll() substitutes every instance of the target substring.',
      },
      {
        id: 'opt-b',
        codeReplacement: '  return sentence.replace("bad", "good", "all");',
        explanation: 'replace() does not accept a 3rd string parameter for flags.',
      },
      {
        id: 'opt-c',
        codeReplacement: '  return sentence.replace("/bad/", "good");',
        explanation: 'Passing "/bad/" as a string literally searches for the slashes.',
      },
      {
        id: 'opt-d',
        codeReplacement: '  return sentence.split("bad").toString();',
        explanation: 'toString() joins with commas, creating "good, vibes make , days".',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Why was only the first "bad" replaced?',
      'String.replace(string, ...) replaces ONLY the very first match.',
      'Use `sentence.replaceAll("bad", "good")` or a regex with the `/g` flag.',
    ],
    explanation:
      'In JavaScript, passing a string to `replace()` only replaces the first occurrence found. Modern JS provides `replaceAll()` to replace all matches.',
    creature: {
      id: 'c-globalglitch',
      name: 'Globalglitch',
      species: 'One-Shot Fairy',
      rarity: 'common',
      description: 'Casts its spell once and immediately falls asleep for the rest of the sentence.',
      avatarEmoji: '🧚',
    },
  },
];
