import type { BugPuzzle } from '../types';

export const PYTHON_PUZZLES: BugPuzzle[] = [
  {
    id: 'py-01-off-by-one',
    title: 'Countdown Blastoff',
    language: 'python',
    category: 'off_by_one',
    difficulty: 1,
    concept: 'range() stop value boundary',
    brief: 'Print a countdown from 3 down to 1, followed by Blastoff!',
    buggyCode: `def countdown():\n    for i in range(3, 1, -1):\n        print(i)\n    print("Blastoff!")\n\ncountdown()`,
    bugLineNumber: 2,
    expectedOutput: '3\n2\n1\nBlastoff!',
    actualOutput: '3\n2\nBlastoff!',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '    for i in range(3, 0, -1):',
        explanation: 'In Python range(start, stop, step), the stop value is exclusive. Using 0 includes 1.',
      },
      {
        id: 'opt-b',
        codeReplacement: '    for i in range(3, 1):',
        explanation: 'Default step is +1, which would produce an empty range when starting at 3.',
      },
      {
        id: 'opt-c',
        codeReplacement: '    for i in range(3, -1, -1):',
        explanation: 'Stopping at -1 would print 0 as well, but the brief stops at 1.',
      },
      {
        id: 'opt-d',
        codeReplacement: '    for i in [3, 2]:',
        explanation: 'Hardcoding a list misses 1 entirely.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Take a close look at the stop parameter in range(start, stop, step).',
      'Remember that Python range() never includes the stop value itself.',
      'To include the number 1 when counting down, the stop argument must be 0.',
    ],
    explanation:
      'Python range(start, stop, step) is half-open: [start, stop). When stepping downwards by -1, to count down to 1, the stop threshold must be 0 so 1 is included.',
    creature: {
      id: 'c-sliceworm',
      name: 'Sliceworm',
      species: 'Annelid',
      rarity: 'common',
      description: 'Lurks at slice and range boundaries, eating the final number!',
      avatarEmoji: '🐛',
    },
  },
  {
    id: 'py-02-type-error',
    title: 'Player Score Tag',
    language: 'python',
    category: 'type_error',
    difficulty: 1,
    concept: 'Implicit type conversion in concatenation',
    brief: 'Display a player name combined with their score.',
    buggyCode: `def format_score(player, score):\n    return player + ": " + score\n\nprint(format_score("Alex", 100))`,
    bugLineNumber: 2,
    expectedOutput: 'Alex: 100',
    actualOutput: 'TypeError: can only concatenate str (not "int") to str',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '    return f"{player}: {score}"',
        explanation: 'An f-string automatically converts the integer score into a string safely.',
      },
      {
        id: 'opt-b',
        codeReplacement: '    return player + score',
        explanation: 'Still attempts to concatenate a string with an integer without delimiter.',
      },
      {
        id: 'opt-c',
        codeReplacement: '    return int(player) + score',
        explanation: 'Converting player "Alex" to int raises a ValueError.',
      },
      {
        id: 'opt-d',
        codeReplacement: '    return str(player + ": ") + score',
        explanation: 'The score is still an integer being added to a string.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Notice the types: player is a str, but score is an int.',
      'In Python, unlike JavaScript, adding a string to an integer does not auto-coerce.',
      'Use an f-string or str(score) to format non-string values into text.',
    ],
    explanation:
      'Python is strongly typed and will not implicitly convert integers to strings during the + operation. F-strings (f"{player}: {score}") or str() must be used.',
    creature: {
      id: 'c-concatan',
      name: 'Concatan',
      species: 'Feline Glitch',
      rarity: 'common',
      description: 'Refuses to glue numbers and words together without proper casting spells.',
      avatarEmoji: '🐱',
    },
  },
  {
    id: 'py-03-index-error',
    title: 'Top Medalist',
    language: 'python',
    category: 'string_indexing',
    difficulty: 1,
    concept: '0-based list indexing vs length',
    brief: 'Retrieve the last runner from a 3-person list.',
    buggyCode: `def get_last_place(runners):\n    return runners[len(runners)]\n\nnames = ["Ada", "Grace", "Linus"]\nprint(get_last_place(names))`,
    bugLineNumber: 2,
    expectedOutput: 'Linus',
    actualOutput: 'IndexError: list index out of range',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '    return runners[-1]',
        explanation: 'Negative indexing [-1] cleanly and safely accesses the last element.',
      },
      {
        id: 'opt-b',
        codeReplacement: '    return runners[len(runners) + 1]',
        explanation: 'Increasing the index goes even further out of bounds.',
      },
      {
        id: 'opt-c',
        codeReplacement: '    return runners[0]',
        explanation: 'runners[0] returns the first runner "Ada", not the last.',
      },
      {
        id: 'opt-d',
        codeReplacement: '    return runners[3]',
        explanation: 'For a 3-element list, index 3 is out of range.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Lists are indexed starting at 0.',
      'A list with 3 elements has valid indices 0, 1, and 2. len(runners) evaluates to 3.',
      'Use negative indexing [-1] or len(runners) - 1 to access the final element.',
    ],
    explanation:
      'Because Python lists are zero-indexed, an N-element list has indices 0 through N-1. Accessing index N raises IndexError. Python provides [-1] as the idiomatic shortcut.',
    creature: {
      id: 'c-indexo',
      name: 'Indexo',
      species: 'Boundary Crab',
      rarity: 'common',
      description: 'Pinches any finger reaching one step past the edge of an array.',
      avatarEmoji: '🦀',
    },
  },
  {
    id: 'py-04-mutable-default',
    title: 'Shopping Cart Accumulator',
    language: 'python',
    category: 'logic_error',
    difficulty: 2,
    concept: 'Default mutable arguments binding at definition time',
    brief: 'Create a new independent cart for each shopper.',
    buggyCode: `def add_item(item, cart=[]):\n    cart.append(item)\n    return cart\n\nprint(add_item("Apple"))\nprint(add_item("Banana"))`,
    bugLineNumber: 1,
    expectedOutput: "['Apple']\n['Banana']",
    actualOutput: "['Apple']\n['Apple', 'Banana']",
    options: [
      {
        id: 'opt-a',
        codeReplacement: 'def add_item(item, cart=None):',
        explanation: 'Using None as default and initializing inside the function avoids shared state.',
      },
      {
        id: 'opt-b',
        codeReplacement: 'def add_item(item, cart=list()):',
        explanation: 'list() in default args is still evaluated only once at definition time.',
      },
      {
        id: 'opt-c',
        codeReplacement: 'def add_item(item, cart=[""]):',
        explanation: 'Still a mutable list default, and adds an empty string.',
      },
      {
        id: 'opt-d',
        codeReplacement: 'def add_item(item, cart=()):',
        explanation: 'A tuple is immutable, so calling .append() would raise an AttributeError.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Why did Banana get added to the same cart that contained Apple?',
      'Default parameter values in Python are evaluated once when the function is defined, not per call.',
      'The standard Python idiom is `cart=None`, followed by `if cart is None: cart = []`.',
    ],
    explanation:
      'In Python, default arguments are evaluated once when the function definition is executed. A mutable object like a list is shared across all function invocations.',
    creature: {
      id: 'c-listphantom',
      name: 'Listphantom',
      species: 'Memory Poltergeist',
      rarity: 'rare',
      description: 'Quietly preserves old baggage between calls using persistent memory portals.',
      avatarEmoji: '👻',
    },
  },
  {
    id: 'py-05-zero-division',
    title: 'Average Test Score',
    language: 'python',
    category: 'logic_error',
    difficulty: 2,
    concept: 'Empty collection guard and division by zero',
    brief: 'Calculate the average score of a list, returning 0 if empty.',
    buggyCode: `def calc_average(scores):\n    return sum(scores) / len(scores)\n\nempty_scores = []\nprint(calc_average(empty_scores))`,
    bugLineNumber: 2,
    expectedOutput: '0',
    actualOutput: 'ZeroDivisionError: division by zero',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '    return sum(scores) / len(scores) if scores else 0',
        explanation: 'Guards against division by zero by checking if the list is truthy (non-empty).',
      },
      {
        id: 'opt-b',
        codeReplacement: '    return sum(scores) / (len(scores) + 1)',
        explanation: 'Skewers the math for non-empty lists by dividing by the wrong number.',
      },
      {
        id: 'opt-c',
        codeReplacement: '    return sum(scores) // len(scores)',
        explanation: 'Floor division // still raises ZeroDivisionError when dividing by 0.',
      },
      {
        id: 'opt-d',
        codeReplacement: '    return 0',
        explanation: 'Returns 0 for all lists, destroying average calculation.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'What is the length of an empty list []?',
      'Dividing any number by 0 immediately crashes Python with ZeroDivisionError.',
      'Check if the collection has items before calculating the division.',
    ],
    explanation:
      'len([]) is 0, making division impossible. Using a conditional expression `if scores else 0` provides a graceful default for empty datasets.',
    creature: {
      id: 'c-divzero',
      name: 'Divzero',
      species: 'Singularity Imp',
      rarity: 'rare',
      description: 'Collapses calculations into black holes whenever a zero touches the bottom.',
      avatarEmoji: '🕳️',
    },
  },
  {
    id: 'py-06-variable-scope',
    title: 'Global High Score',
    language: 'python',
    category: 'variable_scope',
    difficulty: 2,
    concept: 'Local vs global variable assignment in functions',
    brief: 'Update the global top score when a higher score is achieved.',
    buggyCode: `high_score = 50\n\ndef record_score(score):\n    if score > high_score:\n        high_score = score\n\nrecord_score(80)\nprint(high_score)`,
    bugLineNumber: 4,
    expectedOutput: '80',
    actualOutput: 'UnboundLocalError: cannot access local variable',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '        global high_score; high_score = score',
        explanation: 'Declaring global high_score tells Python to modify the module-level variable.',
      },
      {
        id: 'opt-b',
        codeReplacement: '        score = high_score',
        explanation: 'This reassigns the local argument score instead of updating high_score.',
      },
      {
        id: 'opt-c',
        codeReplacement: '        high_score == score',
        explanation: 'Comparison operator == does not perform an assignment.',
      },
      {
        id: 'opt-d',
        codeReplacement: '        pass',
        explanation: 'Pass does nothing, leaving high_score unchanged at 50.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Notice that high_score is assigned to inside the function.',
      'Python marks any variable assigned inside a function as local unless declared global.',
      'Use the `global` keyword to instruct Python that high_score lives outside.',
    ],
    explanation:
      'Because `high_score = score` exists in the function body, Python treats `high_score` as local. Reading it in `if score > high_score` before assignment causes UnboundLocalError.',
    creature: {
      id: 'c-scopegeist',
      name: 'Scopegeist',
      species: 'Boundary Wraith',
      rarity: 'epic',
      description: 'Erects invisible walls between function scopes, trapping global data outside.',
      avatarEmoji: '🔮',
    },
  },
  {
    id: 'py-07-infinite-loop',
    title: 'Loading Progress',
    language: 'python',
    category: 'infinite_loop',
    difficulty: 1,
    concept: 'Loop counter incrementation',
    brief: 'Print steps 0, 1, 2 and terminate.',
    buggyCode: `def step_counter():\n    step = 0\n    while step < 3:\n        print(step)\n\nstep_counter()`,
    bugLineNumber: 4,
    expectedOutput: '0\n1\n2',
    actualOutput: '0\n0\n0\n... (infinite loop)',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '        print(step); step += 1',
        explanation: 'Incrementing the counter by 1 allows the while condition to eventually terminate.',
      },
      {
        id: 'opt-b',
        codeReplacement: '        step = 3',
        explanation: 'Immediately jumps to 3, failing to print steps 1 and 2.',
      },
      {
        id: 'opt-c',
        codeReplacement: '        print(step + 1)',
        explanation: 'Prints step + 1 but still never changes step itself, looping infinitely.',
      },
      {
        id: 'opt-d',
        codeReplacement: '        return step',
        explanation: 'Exits after the first iteration, printing only 0.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'What value does `step` hold after the first iteration?',
      'Since step never changes, `step < 3` remains True forever.',
      'Advance the loop variable using `step += 1`.',
    ],
    explanation:
      'While loops evaluate condition `step < 3` before every iteration. If the body never updates the condition variable, the loop runs forever.',
    creature: {
      id: 'c-loopo',
      name: 'Ouroboros Loopo',
      species: 'Infinite Serpent',
      rarity: 'common',
      description: 'Chases its own tail endlessly until CPU temperatures boil.',
      avatarEmoji: '🐍',
    },
  },
  {
    id: 'py-08-key-error',
    title: 'Inventory Lookup',
    language: 'python',
    category: 'null_undefined',
    difficulty: 1,
    concept: 'Safe dictionary key lookup',
    brief: 'Look up potions in inventory, returning 0 if none found.',
    buggyCode: `def get_potion_count(inventory):\n    return inventory["potions"]\n\nhero_bag = {"gold": 15}\nprint(get_potion_count(hero_bag))`,
    bugLineNumber: 2,
    expectedOutput: '0',
    actualOutput: "KeyError: 'potions'",
    options: [
      {
        id: 'opt-a',
        codeReplacement: '    return inventory.get("potions", 0)',
        explanation: 'dict.get(key, default) safely returns 0 when the key is absent.',
      },
      {
        id: 'opt-b',
        codeReplacement: '    return inventory["potions"] or 0',
        explanation: 'Direct indexing [] still raises KeyError before or can execute.',
      },
      {
        id: 'opt-c',
        codeReplacement: '    return inventory[0]',
        explanation: 'Dictionaries are keyed by hashable keys, not numerical indices.',
      },
      {
        id: 'opt-d',
        codeReplacement: '    return "potions" in inventory',
        explanation: 'Returns a boolean False instead of the requested count 0.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'hero_bag only contains "gold", not "potions".',
      'Direct dictionary subscripting `dict[key]` throws KeyError on missing keys.',
      'Use the `.get()` method which accepts a fallback default value.',
    ],
    explanation:
      'In Python, `dict[missing_key]` raises a KeyError. The safe idiom is `dict.get(key, fallback)`, which returns the fallback if the key is not found.',
    creature: {
      id: 'c-keygoblin',
      name: 'Keygoblin',
      species: 'Loot Gremlin',
      rarity: 'common',
      description: 'Shuts dungeon doors with a loud screech whenever the wrong key is tried.',
      avatarEmoji: '🗝️',
    },
  },
  {
    id: 'py-09-indentation',
    title: 'Sum of Evens',
    language: 'python',
    category: 'syntax_error',
    difficulty: 1,
    concept: 'Python block indentation scope',
    brief: 'Sum only even numbers from a list.',
    buggyCode: `def sum_evens(nums):\n    total = 0\n    for n in nums:\n        if n % 2 == 0:\n        total += n\n    return total`,
    bugLineNumber: 5,
    expectedOutput: '6',
    actualOutput: 'IndentationError: expected an indented block',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '            total += n',
        explanation: 'Indenting by 4 spaces places the statement inside the if branch.',
      },
      {
        id: 'opt-b',
        codeReplacement: '    total += n',
        explanation: 'Aligning with the def body is invalid inside a for loop.',
      },
      {
        id: 'opt-c',
        codeReplacement: '  total += n',
        explanation: 'Inconsistent 2-space indentation raises IndentationError.',
      },
      {
        id: 'opt-d',
        codeReplacement: 'total += n',
        explanation: 'Zero indentation treats it as global code.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Look at line 4: `if n % 2 == 0:`. Python requires a colon followed by an indented block.',
      'Line 5 is at the same indentation level as line 4.',
      'Indent line 5 four spaces deeper so it belongs to the if body.',
    ],
    explanation:
      'Python uses whitespace indentation to define code blocks. After any statement ending in a colon `:`, the following block must be indented.',
    creature: {
      id: 'c-tabsneak',
      name: 'Tabsneak',
      species: 'Whitespace Chameleon',
      rarity: 'common',
      description: 'Swallows indentation spaces when your back is turned.',
      avatarEmoji: '📐',
    },
  },
  {
    id: 'py-10-string-mutation',
    title: 'Capitalize First Letter',
    language: 'python',
    category: 'type_error',
    difficulty: 2,
    concept: 'String immutability in Python',
    brief: 'Replace the first letter with an uppercase character.',
    buggyCode: `def cap_first(word):\n    word[0] = word[0].upper()\n    return word\n\nprint(cap_first("hello"))`,
    bugLineNumber: 2,
    expectedOutput: 'Hello',
    actualOutput: "TypeError: 'str' object does not support item assignment",
    options: [
      {
        id: 'opt-a',
        codeReplacement: '    return word[0].upper() + word[1:]',
        explanation: 'Constructs a new string from the upper initial plus the remaining slice.',
      },
      {
        id: 'opt-b',
        codeReplacement: '    word.replace(word[0], word[0].upper())',
        explanation: 'replace() would replace all occurrences of "h" and is not returned.',
      },
      {
        id: 'opt-c',
        codeReplacement: '    setattr(word, 0, word[0].upper())',
        explanation: 'Strings are immutable primitives; setattr cannot modify character items.',
      },
      {
        id: 'opt-d',
        codeReplacement: '    word[0] == word[0].upper()',
        explanation: 'Performs a boolean comparison rather than updating the string.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'In Python, can you change a single character of a string in-place?',
      'Strings in Python are immutable — once created, their characters cannot be modified.',
      'Build a new string using slicing: `word[0].upper() + word[1:]`.',
    ],
    explanation:
      'Python strings are immutable. You cannot assign to `s[0]`. Modifications require slicing and building a new string object.',
    creature: {
      id: 'c-immutaspider',
      name: 'Immutaspider',
      species: 'Crystal Arachnid',
      rarity: 'rare',
      description: 'Spins unbreakable crystal strings that shatter if you try to mutate a single bead.',
      avatarEmoji: '🕷️',
    },
  },
  {
    id: 'py-11-shallow-copy',
    title: 'Duplicate High Scores',
    language: 'python',
    category: 'array_mutation',
    difficulty: 2,
    concept: 'Variable assignment reference vs list copy',
    brief: 'Create a backup of scores, then append a bonus to original only.',
    buggyCode: `def backup_scores(original):\n    backup = original\n    original.append(99)\n    return backup\n\nscores = [10, 20]\nprint(backup_scores(scores))`,
    bugLineNumber: 2,
    expectedOutput: '[10, 20]',
    actualOutput: '[10, 20, 99]',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '    backup = original.copy()',
        explanation: 'list.copy() creates a new shallow copy of the list instead of copying the pointer.',
      },
      {
        id: 'opt-b',
        codeReplacement: '    backup = list',
        explanation: 'Assigns the built-in type object `list`, not the copied items.',
      },
      {
        id: 'opt-c',
        codeReplacement: '    backup = &original',
        explanation: '& is bitwise AND; Python does not have a C-style address-of operator.',
      },
      {
        id: 'opt-d',
        codeReplacement: '    backup = original[:0]',
        explanation: 'original[:0] returns an empty list `[]`.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Why did modifying `original` also change `backup`?',
      'In Python, assignment `b = a` assigns a reference to the same list in memory.',
      'Use `.copy()` or `original[:]` to produce an independent copy.',
    ],
    explanation:
      'Assignment statements in Python do not copy objects; they bind names to the existing object. For mutable sequences like lists, use `.copy()` or `list[:]`.',
    creature: {
      id: 'c-clonetangle',
      name: 'Clonetangle',
      species: 'Doppelganger Slime',
      rarity: 'epic',
      description: 'Ties two variables to the same physical memory cord with invisible threads.',
      avatarEmoji: '👥',
    },
  },
  {
    id: 'py-12-comparison',
    title: 'Check Exact Match',
    language: 'python',
    category: 'comparison_error',
    difficulty: 2,
    concept: 'Identity (is) vs Equality (==) in Python',
    brief: 'Check if two calculated strings have the same content.',
    buggyCode: `def check_match(s1, s2):\n    return s1 is s2\n\nword_a = "hello world"\nword_b = "hello " + "world"\nprint(check_match(word_a, word_b))`,
    bugLineNumber: 2,
    expectedOutput: 'True',
    actualOutput: 'False',
    options: [
      {
        id: 'opt-a',
        codeReplacement: '    return s1 == s2',
        explanation: 'The equality operator == checks value equality, which is what string comparison needs.',
      },
      {
        id: 'opt-b',
        codeReplacement: '    return s1 = s2',
        explanation: 'Single = is an assignment statement, which is invalid in a return expression.',
      },
      {
        id: 'opt-c',
        codeReplacement: '    return id(s1) == id(s2)',
        explanation: 'Comparing id() tests identity just like `is`, which fails for non-interned strings.',
      },
      {
        id: 'opt-d',
        codeReplacement: '    return s1 in s2',
        explanation: 'in tests substring containment, not whether both strings are identical.',
      },
    ],
    correctOptionId: 'opt-a',
    hints: [
      'Notice the difference between `is` and `==`.',
      '`is` checks memory identity (same memory address). `==` checks value equality.',
      'Two strings can have identical characters while living at different memory locations.',
    ],
    explanation:
      '`is` tests whether two references point to the exact same object in memory. `==` tests whether the values are equal. For string content comparisons, always use `==`.',
    creature: {
      id: 'c-identitybat',
      name: 'Identitybat',
      species: 'Echo Bat',
      rarity: 'rare',
      description: 'Confuses matching echoes with identical physical bats.',
      avatarEmoji: '🦇',
    },
  },
];
